sudo: required
services:
  - docker

before_install:
  - docker build -t weslleydavid/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true weslleydavid/react-test npm test -- --coverage

after_success:
  - docker build -t weslleydavid/multi-client ./client
  - docker build -t weslleydavid/multi-nginx ./nginx
  - docker build -t weslleydavid/multi-server ./server
  - docker build -t weslleydavid/multi-worker ./worker
  # log in to the docker Cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push weslleydavid/multi-client
  - docker push weslleydavid/multi-nginx
  - docker push weslleydavid/multi-server
  - docker push weslleydavid/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'sa-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-sa-east-1-421763509082'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY